# Generated by Django 4.2 on 2023-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapi', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
